import type { Metadata } from "next";
import { Inter, Figtree } from 'next/font/google'
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Link from "next/link";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Terminal } from "lucide-react";

const inter = Inter({ subsets: ['latin'] })
// const figtree = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased h-screen grid grid-rows-[max-content_1fr_max-content]`}
        style={{
          // bacrgb(216,208,231)kground: 'rgb(248,244,255)',
          background: 'radial-gradient(circle at center top, rgba(233,240,255,1) 0%, rgba(255,255,255,1) 35%, rgba(255,255,255,1) 100%)',
        }}
      >
        {/* <Alert className="bg-secondary text-muted-foreground h-fit flex justify-center items-center rounded-none border-none">
          <AlertDescription className="text-center">
            Masih dalam tahap pengembangan, lihat selengkapnya disini.
          </AlertDescription>
        </Alert> */}

        <Navbar />
        <main className="container max-w-[925px]">
          {children}
        </main>
        <footer className="w-full flex justify-center p-5 relative bottom-0">
          <div>
            Built with <span className="text-red-500">&hearts;</span> by <Link href={'https://www.instagram.com/falll.hkm/'} target="_blank" className="text-blue-600">@falll.hkm</Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
